server:
  port: 8090
spring:
  application:
    name: taco-cloud
  datasource:
    generate-unique-name: false #сообщаем что не нужно генерировать уникальные значения для ссылки бд
    url: jdbc:h2:file:D:/LocalProjects/IDEA/taco-cloud-data/taco-cloud-data-base
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
#      ddl-auto: validate
#      ddl-auto: create-drop
